Readme + ressource semaine 1 session 2
konexio/digistart pull request #3
Opened 2019-02-16 14:22 UTC by fhenri42

Mise a jour des exercices plus du cours de la session 2

Vous pouvez retrouvez le ppt sur ce lien => https://docs.google.com/presentation/d/1_P6GsbWISu9vZsg5pph79nIQ5T2oJo8fQ6exgZQ_wjE/edit#slide=id.g37ff2d11d2_1_148

2019-02-17 07:27 UTC, GhizlaneAroussi requested changes
Hello,
J'ai fait quelques suggestions d'amélioration.
Ghizlane

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/bonus.js
> +function isValidNbr (nbr) {
Un tout petit problème d'indentation

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/bonus.js
> +    }
Il vaut mieux sauter une ligne entre les fonctions et pas après le nom de la fonction, pour la clarté du document.

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/ex02.html
> +
Toujours dans l'optique de leur rendre la lecture du fichier simple, c'est mieux de mettre des classes ou des ids, et mettre les styles dans un fichier css à part. Qu'en penses-tu ?

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/ex02.html
> +      <div style=" isplay: flex; flex-direction: colomun; justify-content: space-between;border-style: dotted; width: 250px; padding: 10">
un "d" a sauté au display ;)

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/ex02.html
> +  <script src=”index.js”></script>
pourquoi ne pas mettre le script dans le head du fichier ? comme ils ont appris à le faire pour le css ?

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/ex02.js
> +
Pour les aider plus à se retrouver, il faut peut-être ajouter les instructions sous forme de commentaires comme ceci:

// TODO: Ajouter ici le contenu de la fonction sub qui va faire la soustraction
// TODO: Ajouter ici le contenu de la fonction mul qui va faire la multiplication
etc

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/exo1.html
> +    <div style="display:flex; flex-direction: column; width:100px;">
même remarque pour les syles dans un fichier à part

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/exo1.html
> +    <script src="./index.js">
et même remarque pour le script plutôt dans <head>

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/src/exo1.js
> +function firstEvent() {
c'est la solution du coup, il n'y a pas de fichier avec juste les noms de fonctions des des commentaires //TODO d'instructions ?

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/README.md
> +* 2)En utilisant  l'événement onkeydown, crée une fonction qui affiche chaque carette que l'utilisateur appuis
typo: appuie

2019-02-17 07:27 UTC, GhizlaneAroussi commented on Javascript/week1/session2/README.md
> +### Exercice 1
J'ai retenu de notre réunion qu'on allait faire un dossier par exercice, du coup il y aurait le readme de la sessions qui présenterait la thématique et tout ça, et un readme par exercice pour les instructions, non ? ça couperait ce fichier en deux si c'est le cas

2019-02-19 22:17 UTC, merged

2019-02-20 21:31 UTC, darahak commented
Il ne fallait pas merge cette PR, la review était en cours.
@fhenri42 Tu peux appliquer les modifs et ouvrir une autre PR ?

2019-02-23 05:32 UTC, fhenri42 commented
Yes je m'en occupe.