Simon - Exercices pour S02E01 et S02E02
konexio/digistart pull request #6
Opened 2019-02-21 20:23 UTC by SimonGodefroid

Hello tout le monde,

J'ai rajouté mes exos, il faut que je vois ce que je mets dans les README...
Aussi j'ai inversé l'ordre des exercices entre le 2 et le 3.
J'avais espoir de mettre des bonus ou de leur faire utiliser typeof mais pour l'instant j'ai laissé comme ça.

2019-02-23 08:12 UTC, GhizlaneAroussi requested changes
Hello, je n'ai pas fait une review complète, j'ai juste parcouru très vite. Le commentaire qui reviendra le plus est d'utiliser l'infinitif pour les instructions.

J'ai remarqué que le format est un peu différent de ce qu'on avait dit pendant la réunion, et qui est: un dossier par exercice, avec dans le dossier, un js, un html, et un readme où on retrouve les instructions qui sont dans le code sous forme de commentaires.

L'intérêt de ton format est qu'ils n'ont pas besoin d'ouvrir le source du html, ils ont besoin uniquement du js et de la page dans le browser. Mais en même temps, pour bien comprendre d'où vient l'id qu'ils utilisent en JS, il vaut mieux qu'ils lisent le html dans le source, sauf qu'avec toutes les instructions dedans, ça pourrait être compliqué à lire.
Je ne sais pas s'il faut que tu changes le format pour rester conforme à ce qu'on avait dit, ou  si on laisse comme ça pour tester avec les apprenants ce qu'ils préfèrent et choisir pour la session suivante.

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo1.html
> +            <br />Tips: Il faudra utiliser les if, else et else if...
Utilise peut-être "Astuce" au lieu de tips

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo1.html
> +
De manière générale, on utilise l'infinitif dans le cours pour les instructions. Ce serait mieux de le garder dans tout le cours pour avoir une cohérence

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo1.js
> +  // document.body.style.backgroundColor = 'la-couleur-en-css';
Ils risquent de chercher 'la-couleur-en-css', il vaut mieux mettre juste un '...'

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo1.js
> +  // CONSIGNE:
Même remarque que pour le html: il vaut mieux utiliser l'infinitif pour les consignes

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo2.correction.js
> +  console.log('longeur du mot de passe: ', value.length);
typo : longueur

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo2.correction.js
> +    document.getElementById('password-input').style.backgroundColor = '';
du coup si c'est 0 il devient red puis rien ? il faut peut être ajouter la condition && > 0 dans le premier "if"

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo2.html
> +
Pareil: infinitif pour les instructions

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo2.html
> +          <p>Va dans le fichier index.js et écris le code là où c'est indiqué, pour pouvoir changer
exo2.js ?

2019-02-23 08:12 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo2.js
> +  // Cette partie du code te permets de voir la longueur du mot de passe saisi par l'utilisateur
"Cette partie du code permet" + infinitif partout

2019-02-23 12:35 UTC, SimonGodefroid commented on Javascript/week2/session1/src/exo1.js
> +  // CONSIGNE:
Infinitif ou troisième personne ?
e.g. cette partie du code permet de voir ce qu'à choisi l'utilisateur
cette partie du code va permettre de...

En fait est-ce que c'est le fait de s'adresser à eux directement qu'il faut changer ou le temps des instructions?

2019-02-23 12:47 UTC, SimonGodefroid commented
> Le commentaire qui reviendra le plus est d'utiliser l'infinitif pour les instructions.

=> je vais changer ça

> un dossier par exercice, avec dans le dossier, un js, un html, et un readme

=> j'ai complètement zappé je vais le faire et je mettrais je pense dans le README à peu près la même chose que ce que j'ai mis en commentaire.

> L'intérêt de ton format.... 

En fait pour moi ils ouvriront le navigateur avec index.html qui tourne + vscode avec dedans index.html et index.js + le readme éventuellement (soit dans vscode soit sur github).

Dans l'idéal, j'aimerai autant qu'ils soient uniquement entre vscode et index.html dans browser mais on verra.

L'intérêt d'avoir les commentaires et le readme c'est qu'ils pourront choisir eux-mêmes.

2019-02-23 13:21 UTC, SimonGodefroid commented on Javascript/week2/session1/src/exo2.correction.js
> +    document.getElementById('password-input').style.backgroundColor = '';
En fait si l'input est vide il n'y a que le placeholder.
J'ai rajouté la condition && passwordLength >0 ça n'a rien changé.

2019-02-24 15:04 UTC, darahak commented
N'hésitez pas à rappeler les thèmes de vos cours et exercices dans vos PR.
Celle-ci porte sur les conditions, mais je ne savais pas si je devais m'attendre à voir quelque chose sur les types en plus.

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex1/README.md
> +## EXERCICE 1 - CHANGE LA COULEUR DE FOND DU BODY
- Je serais pour éviter le caps lock, juste pour une question de consistence avec ce que j'ai déjà vu avant (i.e. la partie de @GhizlaneAroussi).
- Utiliser l'infinitif pour être raccord avec le reste aussi.
- Mieux exploiter le formatage en Markdown (niveaux de header, emphase sur certains termes).

```suggestion
# Exercice 1 - Changer la couleur de fond du `body`
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex1/README.md
> +### OBJECTIF:
```suggestion
## Objectif
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex1/README.md
> +avec if else et else if pour changer la couleur de fond du body
```suggestion
avec `if`, `else` et `else if` pour changer la couleur de fond du `body`.
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex1/README.md
> +## Consigne:
Je m'inquiète probablement pour rien, mais ça peut être plus facile à comprendre pour les anglophones qui ne maîtrisent pas encore le français, car il a le même sens dans les deux langues.

```suggestion
## Instructions
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex1/README.md
> +la valeur qu'a choisi l'utilisateur, en utilisant des conditions (**if**, **else**, ou **else if**)
```suggestion
la valeur qu'a choisi l'utilisateur, en utilisant des conditions (**if**, **else**, ou **else if**).
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex1/index.html
> +          <p>Aller dans le fichier index.js et écrire le code là où c'est indiqué, pour pouvoir changer
```suggestion
<p>Aller dans le fichier index.js et écrire le code à l'endroit indiqué, pour changer
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex1/index.js
> +  // cette partie du code permet de voir ce qu'a choisi l'utilisateur
```suggestion
  // Cette ligne de code permet d'afficher le choix de l'utilisateur dans la console du navigateur.
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex2/README.md
> +## EXERCICE 2 - PASSWORD METER
Question de consistence également : essayer de trouver un titre en français.

```suggestion
# Exercice 2 - Indicateur de longueur d'un mot de passe
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex2/README.md
> +### OBJECTIF:
```suggestion
## Objectif
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex2/README.md
> +Cet exercice a pour but de faire utiliser les conditions et les comparateurs pour changer la couleur de l'input
```suggestion
Cet exercice a pour but de faire utiliser les conditions et les comparateurs pour changer la couleur du champ où l'utilisateur écrira son mot de passe.
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex2/README.md
> +### Consigne:
Comme pour l'exo 1.

```suggestion
## Instructions
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex2/README.md
> +Les règles sont les suivantes
```suggestion
Les règles sont les suivantes :
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session1/src/ex2/index.html
> +          <p>Aller dans le fichier index.js et écrire le code là où c'est indiqué, pour pouvoir changer
```suggestion
          <p>Aller dans le fichier index.js et écrire le code à l'endroit indiqué, pour changer
```

2019-02-24 15:35 UTC, darahak commented on Javascript/week2/session2/src/ex3/README.md
> +/_ EXERCICE 3 - LE JUSTE PRIX DU MERCATO _/
Fichier à formater en Markdown.

2019-02-24 18:21 UTC, GhizlaneAroussi commented on Javascript/week2/session1/src/exo1.js
> +  // CONSIGNE:
Les deux: par exemple au lieu de dire "va dans le fichier javascript et change la ligne ...", "Dans le fichier javascript, changer la ligne ..."

2019-02-25 18:56 UTC, SimonGodefroid commented on Javascript/week2/session2/src/ex3/README.md
> +/_ EXERCICE 3 - LE JUSTE PRIX DU MERCATO _/
Done

2019-02-25 18:56 UTC, SimonGodefroid commented on Javascript/week2/session1/src/ex2/index.html
> +          <p>Aller dans le fichier index.js et écrire le code là où c'est indiqué, pour pouvoir changer
cheers

2019-02-25 18:56 UTC, SimonGodefroid commented on Javascript/week2/session1/src/ex2/README.md
> +Les règles sont les suivantes
cheers

2019-02-25 18:57 UTC, SimonGodefroid commented on Javascript/week2/session1/src/exo1.html
> +            <br />Tips: Il faudra utiliser les if, else et else if...
done

2019-02-25 19:14 UTC, SimonGodefroid commented
Si vous voulez review le cours...
https://docs.google.com/presentation/d/1_XBT6Zs_gc2kAANPpX_B8M8xs5Dc2oWh_-6xaXq0fVw/edit?usp=sharing

Mais je n'aurai pas la foi/le temps de repasser dessus je pense.

2019-02-26 21:26 UTC, darahak approved these changes

2019-02-26 21:26 UTC, merged