Update week1 => session2
konexio/digistart pull request #9
Opened 2019-02-23 18:05 UTC by fhenri42

Update avec les modifications proposées par Ghizlane dans la PR précédente.

2019-02-23 20:52 UTC, SimonGodefroid reviewed
Okay je me suis planté et j'ai commenté ici mais je ne peux pas supprimer le commentaire.

2019-02-26 07:40 UTC, GhizlaneA requested changes

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/src/bonus/README.md
> +* 3. une fonction pour vérifier si les deux mot de passe sont valide
valides

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/README.md
>  ### Les  differents evenements:
événements

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/src/bonus/bonus.js
> +function isValidNbr (nbr) {
Mais du coup c'est le fichier de solution?

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/src/ex01/README.md
> +* Dans cet exercice vous allez devoir créer 3 éléments Html  qui utilisent des types d'événements différents.
HTML

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/src/ex01/README.md
> +* 1)En utilisant l'événement onclick, crée une fonction qui prévient l'utilisateur a chaque clique sur le bouton
créer ... à chaque ..

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/src/ex01/README.md
> +* 2)En utilisant  l'événement onkeydown, crée une fonction qui affiche chaque carette que l'utilisateur appuie
créer

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/src/ex01/README.md
> +* 3)En utilisant les événements  onmouseover et onmouseout, créer une fonction qui change la couleur d’un carré en rouge quand la sourie est sur le bouton et en bleu quand la sourie sort du bouton
la souris

2019-02-26 07:40 UTC, GhizlaneA commented on Javascript/week1/session2/src/ex02/README.md
> +
le code doit être dans les fichiers de code, avec des instructions sous forme de commentaires

2019-02-26 15:43 UTC, fhenri42 commented on Javascript/week1/session2/src/bonus/bonus.js
> +function isValidNbr (nbr) {
Oui

2019-02-26 20:25 UTC, merged